#!/usr/bin/env python

"""
simplewiki instantiation
"""

import sys
import os
# extend module search path for access to tiddlywebconfig.py
cwd = os.getcwd()
sys.path.insert(0, cwd)

from tiddlyweb.config import config
from tiddlywebplugins.instancer.util import spawn
from tiddlywebplugins.simplewiki import instance as instance_module


def main(args):
    args = [unicode(arg, "UTF-8") for arg in args]
    instance_path = args[1]
    config['instance_tiddlers'] = instance_module.instance_tiddlers
    spawn(instance_path, config, instance_module)
    return True


if __name__ == "__main__":
    status = not main(sys.argv)
    sys.exit(status)
